"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$character"""

[username]
style_user = "bold blue"
format = "[$user]($style)"
show_always = true

[hostname]
style = "bold blue"
format = "[@$hostname]($style) "
ssh_only = false

[directory]
style = "cyan"
format = "[$path]($style) "
truncation_length = 4
truncation_symbol = "…/"

[git_branch]
style = "bold green"
symbol = ""
format = "[$branch]($style)"

[git_status]
style = "bold red"
format = '([ $all_status$ahead_behind]($style)) '
ahead = "↑"
behind = "↓"
diverged = "↕"
staged = "!"
modified = "!"
untracked = "?"
deleted = "✘"
conflicted = "="

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
